[fisher]
plugins = [
    "catppuccin/fish",
    "jhillyerd/plugin-git",
    "jorgebucaran/autopair.fish",
    "jorgebucaran/fisher",
    "patrickf1/fzf.fish",
]

[homebrew]
brews = [
    "bat",
    "chezmoi",
    "choose-rust",
    "fish",
    "fzf",
    "git",
    "lsd",
    "openssh",
    "ripgrep",
    "sd",
    "starship",
    "vivid",
]
casks = [
    "1password",
    "1password-cli",
    "font-maple-mono",
    "font-symbols-only-nerd-font",
    "kitty",
]
