[fisher]
plugins = [
    "catppuccin/fish",
    "jhillyerd/plugin-git",
    "jorgebucaran/autopair.fish",
    "jorgebucaran/fisher",
]

[homebrew]
brews = [
    "chezmoi",
    "choose-rust",
    "fd",
    "fish",
    "git",
    "openssh",
    "ripgrep",
    "sd",
    "starship",
]

casks = [
    "1password",
    "discord",
    "font-maple-mono",
    "font-symbols-only-nerd-font",
    "kitty",
]
